// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: queues_management.proto

package grpcmgmtpb

import (
	protobuf "github.com/clbs-io/octopusmq/api/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_queues_management_proto protoreflect.FileDescriptor

const file_queues_management_proto_rawDesc = "" +
	"\n" +
	"\x17queues_management.proto\x12!io.clbs.octopusmq.grpc.management\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0emessages.proto2\x9a\x04\n" +
	"\x11ManagementService\x12U\n" +
	"\vCreateQueue\x12..io.clbs.octopusmq.protobuf.CreateQueueRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\vResizeQueue\x12..io.clbs.octopusmq.protobuf.ResizeQueueRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\vDeleteQueue\x12..io.clbs.octopusmq.protobuf.DeleteQueueRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\n" +
	"ListQueues\x12\x16.google.protobuf.Empty\x1a..io.clbs.octopusmq.protobuf.ListQueuesResponse\x12S\n" +
	"\n" +
	"PauseQueue\x12-.io.clbs.octopusmq.protobuf.PauseQueueRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\vResumeQueue\x12..io.clbs.octopusmq.protobuf.ResumeQueueRequest\x1a\x16.google.protobuf.EmptyB-Z+github.com/clbs-io/octopusmq/pkg/grpcmgmtpbb\x06proto3"

var file_queues_management_proto_goTypes = []any{
	(*protobuf.CreateQueueRequest)(nil), // 0: io.clbs.octopusmq.protobuf.CreateQueueRequest
	(*protobuf.ResizeQueueRequest)(nil), // 1: io.clbs.octopusmq.protobuf.ResizeQueueRequest
	(*protobuf.DeleteQueueRequest)(nil), // 2: io.clbs.octopusmq.protobuf.DeleteQueueRequest
	(*emptypb.Empty)(nil),               // 3: google.protobuf.Empty
	(*protobuf.PauseQueueRequest)(nil),  // 4: io.clbs.octopusmq.protobuf.PauseQueueRequest
	(*protobuf.ResumeQueueRequest)(nil), // 5: io.clbs.octopusmq.protobuf.ResumeQueueRequest
	(*protobuf.ListQueuesResponse)(nil), // 6: io.clbs.octopusmq.protobuf.ListQueuesResponse
}
var file_queues_management_proto_depIdxs = []int32{
	0, // 0: io.clbs.octopusmq.grpc.management.ManagementService.CreateQueue:input_type -> io.clbs.octopusmq.protobuf.CreateQueueRequest
	1, // 1: io.clbs.octopusmq.grpc.management.ManagementService.ResizeQueue:input_type -> io.clbs.octopusmq.protobuf.ResizeQueueRequest
	2, // 2: io.clbs.octopusmq.grpc.management.ManagementService.DeleteQueue:input_type -> io.clbs.octopusmq.protobuf.DeleteQueueRequest
	3, // 3: io.clbs.octopusmq.grpc.management.ManagementService.ListQueues:input_type -> google.protobuf.Empty
	4, // 4: io.clbs.octopusmq.grpc.management.ManagementService.PauseQueue:input_type -> io.clbs.octopusmq.protobuf.PauseQueueRequest
	5, // 5: io.clbs.octopusmq.grpc.management.ManagementService.ResumeQueue:input_type -> io.clbs.octopusmq.protobuf.ResumeQueueRequest
	3, // 6: io.clbs.octopusmq.grpc.management.ManagementService.CreateQueue:output_type -> google.protobuf.Empty
	3, // 7: io.clbs.octopusmq.grpc.management.ManagementService.ResizeQueue:output_type -> google.protobuf.Empty
	3, // 8: io.clbs.octopusmq.grpc.management.ManagementService.DeleteQueue:output_type -> google.protobuf.Empty
	6, // 9: io.clbs.octopusmq.grpc.management.ManagementService.ListQueues:output_type -> io.clbs.octopusmq.protobuf.ListQueuesResponse
	3, // 10: io.clbs.octopusmq.grpc.management.ManagementService.PauseQueue:output_type -> google.protobuf.Empty
	3, // 11: io.clbs.octopusmq.grpc.management.ManagementService.ResumeQueue:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_queues_management_proto_init() }
func file_queues_management_proto_init() {
	if File_queues_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queues_management_proto_rawDesc), len(file_queues_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queues_management_proto_goTypes,
		DependencyIndexes: file_queues_management_proto_depIdxs,
	}.Build()
	File_queues_management_proto = out.File
	file_queues_management_proto_goTypes = nil
	file_queues_management_proto_depIdxs = nil
}
