// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: raftcommands.proto

package grpcraftcmdpb

import (
	protobuf "github.com/clbs-io/octopusmq/api/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RaftCommand represents a command that will be replicated through the Raft consensus protocol.
type RaftCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*RaftCommand_CreateQueue
	//	*RaftCommand_DeleteQueue
	//	*RaftCommand_PauseResumeQueue
	//	*RaftCommand_PurgeItems
	//	*RaftCommand_StorageCommands
	//	*RaftCommand_StorageDeleteIds
	//	*RaftCommand_StartNoop
	//	*RaftCommand_ResizeQueue
	//	*RaftCommand_CreateStorage
	//	*RaftCommand_DeleteStorage
	Command       isRaftCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCommand) Reset() {
	*x = RaftCommand{}
	mi := &file_raftcommands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCommand) ProtoMessage() {}

func (x *RaftCommand) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCommand.ProtoReflect.Descriptor instead.
func (*RaftCommand) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{0}
}

func (x *RaftCommand) GetCommand() isRaftCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RaftCommand) GetCreateQueue() *RaftCreateQueue {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_CreateQueue); ok {
			return x.CreateQueue
		}
	}
	return nil
}

func (x *RaftCommand) GetDeleteQueue() *protobuf.DeleteQueueRequest {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_DeleteQueue); ok {
			return x.DeleteQueue
		}
	}
	return nil
}

func (x *RaftCommand) GetPauseResumeQueue() *RaftPauseResumeQueue {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_PauseResumeQueue); ok {
			return x.PauseResumeQueue
		}
	}
	return nil
}

func (x *RaftCommand) GetPurgeItems() *RaftPurgeItems {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_PurgeItems); ok {
			return x.PurgeItems
		}
	}
	return nil
}

func (x *RaftCommand) GetStorageCommands() *RaftStorageCommands {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_StorageCommands); ok {
			return x.StorageCommands
		}
	}
	return nil
}

func (x *RaftCommand) GetStorageDeleteIds() *RaftStorageDeleteIds {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_StorageDeleteIds); ok {
			return x.StorageDeleteIds
		}
	}
	return nil
}

func (x *RaftCommand) GetStartNoop() *RaftStartNoop {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_StartNoop); ok {
			return x.StartNoop
		}
	}
	return nil
}

func (x *RaftCommand) GetResizeQueue() *protobuf.ResizeQueueRequest {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_ResizeQueue); ok {
			return x.ResizeQueue
		}
	}
	return nil
}

func (x *RaftCommand) GetCreateStorage() *RaftCreateStorage {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_CreateStorage); ok {
			return x.CreateStorage
		}
	}
	return nil
}

func (x *RaftCommand) GetDeleteStorage() *protobuf.DeleteStorageRequest {
	if x != nil {
		if x, ok := x.Command.(*RaftCommand_DeleteStorage); ok {
			return x.DeleteStorage
		}
	}
	return nil
}

type isRaftCommand_Command interface {
	isRaftCommand_Command()
}

type RaftCommand_CreateQueue struct {
	CreateQueue *RaftCreateQueue `protobuf:"bytes,1,opt,name=create_queue,json=createQueue,proto3,oneof"` // Create a new queue.
}

type RaftCommand_DeleteQueue struct {
	DeleteQueue *protobuf.DeleteQueueRequest `protobuf:"bytes,2,opt,name=delete_queue,json=deleteQueue,proto3,oneof"` // Delete an existing queue.
}

type RaftCommand_PauseResumeQueue struct {
	PauseResumeQueue *RaftPauseResumeQueue `protobuf:"bytes,3,opt,name=pause_resume_queue,json=pauseResumeQueue,proto3,oneof"` // Pause or resume a queue.
}

type RaftCommand_PurgeItems struct {
	PurgeItems *RaftPurgeItems `protobuf:"bytes,4,opt,name=purge_items,json=purgeItems,proto3,oneof"` // Purge items from queues.
}

type RaftCommand_StorageCommands struct {
	// Internal storage commands
	StorageCommands *RaftStorageCommands `protobuf:"bytes,5,opt,name=storage_commands,json=storageCommands,proto3,oneof"` // Batch of storage operations.
}

type RaftCommand_StorageDeleteIds struct {
	StorageDeleteIds *RaftStorageDeleteIds `protobuf:"bytes,6,opt,name=storage_delete_ids,json=storageDeleteIds,proto3,oneof"` // Delete multiple items by ID.
}

type RaftCommand_StartNoop struct {
	// Starting synchronization
	StartNoop *RaftStartNoop `protobuf:"bytes,7,opt,name=start_noop,json=startNoop,proto3,oneof"` // No-op command to sync cluster start time.
}

type RaftCommand_ResizeQueue struct {
	// Queue management commands
	ResizeQueue *protobuf.ResizeQueueRequest `protobuf:"bytes,8,opt,name=resize_queue,json=resizeQueue,proto3,oneof"` // Resize an existing queue.
}

type RaftCommand_CreateStorage struct {
	// Storage management commands
	CreateStorage *RaftCreateStorage `protobuf:"bytes,9,opt,name=create_storage,json=createStorage,proto3,oneof"` // Create a new storage.
}

type RaftCommand_DeleteStorage struct {
	DeleteStorage *protobuf.DeleteStorageRequest `protobuf:"bytes,10,opt,name=delete_storage,json=deleteStorage,proto3,oneof"` // Delete an existing storage.
}

func (*RaftCommand_CreateQueue) isRaftCommand_Command() {}

func (*RaftCommand_DeleteQueue) isRaftCommand_Command() {}

func (*RaftCommand_PauseResumeQueue) isRaftCommand_Command() {}

func (*RaftCommand_PurgeItems) isRaftCommand_Command() {}

func (*RaftCommand_StorageCommands) isRaftCommand_Command() {}

func (*RaftCommand_StorageDeleteIds) isRaftCommand_Command() {}

func (*RaftCommand_StartNoop) isRaftCommand_Command() {}

func (*RaftCommand_ResizeQueue) isRaftCommand_Command() {}

func (*RaftCommand_CreateStorage) isRaftCommand_Command() {}

func (*RaftCommand_DeleteStorage) isRaftCommand_Command() {}

// RaftCreateQueue creates a new queue with an assigned ID.
type RaftCreateQueue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal queue ID assigned by the system.
	QueueId uint32 `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	// Queue creation parameters.
	Queue         *protobuf.CreateQueueRequest `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCreateQueue) Reset() {
	*x = RaftCreateQueue{}
	mi := &file_raftcommands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCreateQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCreateQueue) ProtoMessage() {}

func (x *RaftCreateQueue) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCreateQueue.ProtoReflect.Descriptor instead.
func (*RaftCreateQueue) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{1}
}

func (x *RaftCreateQueue) GetQueueId() uint32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *RaftCreateQueue) GetQueue() *protobuf.CreateQueueRequest {
	if x != nil {
		return x.Queue
	}
	return nil
}

// RaftPauseResumeQueue pauses or resumes a queue.
type RaftPauseResumeQueue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the queue to pause or resume.
	QueueName string `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	// If true, pause the queue; if false, resume it.
	Pause         bool `protobuf:"varint,2,opt,name=pause,proto3" json:"pause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftPauseResumeQueue) Reset() {
	*x = RaftPauseResumeQueue{}
	mi := &file_raftcommands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftPauseResumeQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftPauseResumeQueue) ProtoMessage() {}

func (x *RaftPauseResumeQueue) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftPauseResumeQueue.ProtoReflect.Descriptor instead.
func (*RaftPauseResumeQueue) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{2}
}

func (x *RaftPauseResumeQueue) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *RaftPauseResumeQueue) GetPause() bool {
	if x != nil {
		return x.Pause
	}
	return false
}

// RaftPurgeItems purges expired or completed items from queues.
type RaftPurgeItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftPurgeItems) Reset() {
	*x = RaftPurgeItems{}
	mi := &file_raftcommands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftPurgeItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftPurgeItems) ProtoMessage() {}

func (x *RaftPurgeItems) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftPurgeItems.ProtoReflect.Descriptor instead.
func (*RaftPurgeItems) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{3}
}

// RaftStartNoop is used to synchronize cluster start time and ensure consistency.
type RaftStartNoop struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the cluster started.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Unique identifier for this start operation.
	Uuid          string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftStartNoop) Reset() {
	*x = RaftStartNoop{}
	mi := &file_raftcommands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStartNoop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStartNoop) ProtoMessage() {}

func (x *RaftStartNoop) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStartNoop.ProtoReflect.Descriptor instead.
func (*RaftStartNoop) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{4}
}

func (x *RaftStartNoop) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *RaftStartNoop) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// RaftStorageCommands contains a batch of storage operations to be applied atomically.
type RaftStorageCommands struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal storage ID.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// List of storage commands to execute.
	Commands      []*RaftStorageCommand `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftStorageCommands) Reset() {
	*x = RaftStorageCommands{}
	mi := &file_raftcommands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStorageCommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStorageCommands) ProtoMessage() {}

func (x *RaftStorageCommands) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStorageCommands.ProtoReflect.Descriptor instead.
func (*RaftStorageCommands) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{5}
}

func (x *RaftStorageCommands) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RaftStorageCommands) GetCommands() []*RaftStorageCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

// RaftStorageDeleteIds deletes multiple items by their IDs.
type RaftStorageDeleteIds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of IDs to delete.
	Ids           []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftStorageDeleteIds) Reset() {
	*x = RaftStorageDeleteIds{}
	mi := &file_raftcommands_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStorageDeleteIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStorageDeleteIds) ProtoMessage() {}

func (x *RaftStorageDeleteIds) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStorageDeleteIds.ProtoReflect.Descriptor instead.
func (*RaftStorageDeleteIds) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{6}
}

func (x *RaftStorageDeleteIds) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// RaftStorageCommand represents a single storage operation.
type RaftStorageCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*RaftStorageCommand_Delete
	//	*RaftStorageCommand_Insert
	//	*RaftStorageCommand_Update
	//	*RaftStorageCommand_UpdateMeta
	Command       isRaftStorageCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftStorageCommand) Reset() {
	*x = RaftStorageCommand{}
	mi := &file_raftcommands_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStorageCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStorageCommand) ProtoMessage() {}

func (x *RaftStorageCommand) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStorageCommand.ProtoReflect.Descriptor instead.
func (*RaftStorageCommand) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{7}
}

func (x *RaftStorageCommand) GetCommand() isRaftStorageCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RaftStorageCommand) GetDelete() *RaftStorageDelete {
	if x != nil {
		if x, ok := x.Command.(*RaftStorageCommand_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *RaftStorageCommand) GetInsert() *RaftStorageChange {
	if x != nil {
		if x, ok := x.Command.(*RaftStorageCommand_Insert); ok {
			return x.Insert
		}
	}
	return nil
}

func (x *RaftStorageCommand) GetUpdate() *RaftStorageChange {
	if x != nil {
		if x, ok := x.Command.(*RaftStorageCommand_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *RaftStorageCommand) GetUpdateMeta() *RaftStorageUpdateMetaData {
	if x != nil {
		if x, ok := x.Command.(*RaftStorageCommand_UpdateMeta); ok {
			return x.UpdateMeta
		}
	}
	return nil
}

type isRaftStorageCommand_Command interface {
	isRaftStorageCommand_Command()
}

type RaftStorageCommand_Delete struct {
	Delete *RaftStorageDelete `protobuf:"bytes,1,opt,name=delete,proto3,oneof"` // Delete an item.
}

type RaftStorageCommand_Insert struct {
	Insert *RaftStorageChange `protobuf:"bytes,2,opt,name=insert,proto3,oneof"` // Insert a new item.
}

type RaftStorageCommand_Update struct {
	Update *RaftStorageChange `protobuf:"bytes,3,opt,name=update,proto3,oneof"` // Update an existing item (uses same structure as insert for simplicity).
}

type RaftStorageCommand_UpdateMeta struct {
	UpdateMeta *RaftStorageUpdateMetaData `protobuf:"bytes,4,opt,name=update_meta,json=updateMeta,proto3,oneof"` // Update only the metadata of an item.
}

func (*RaftStorageCommand_Delete) isRaftStorageCommand_Command() {}

func (*RaftStorageCommand_Insert) isRaftStorageCommand_Command() {}

func (*RaftStorageCommand_Update) isRaftStorageCommand_Command() {}

func (*RaftStorageCommand_UpdateMeta) isRaftStorageCommand_Command() {}

// RaftStorageDelete deletes a single item by ID.
type RaftStorageDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the item to delete.
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftStorageDelete) Reset() {
	*x = RaftStorageDelete{}
	mi := &file_raftcommands_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStorageDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStorageDelete) ProtoMessage() {}

func (x *RaftStorageDelete) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStorageDelete.ProtoReflect.Descriptor instead.
func (*RaftStorageDelete) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{8}
}

func (x *RaftStorageDelete) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// RaftStorageChange inserts or updates an item with metadata and data.
type RaftStorageChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the item.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata associated with the item.
	Metadata []byte `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Data content of the item.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftStorageChange) Reset() {
	*x = RaftStorageChange{}
	mi := &file_raftcommands_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStorageChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStorageChange) ProtoMessage() {}

func (x *RaftStorageChange) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStorageChange.ProtoReflect.Descriptor instead.
func (*RaftStorageChange) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{9}
}

func (x *RaftStorageChange) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RaftStorageChange) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RaftStorageChange) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// RaftStorageUpdateMetaData updates only the metadata of an item.
type RaftStorageUpdateMetaData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the item to update.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// New metadata for the item.
	Metadata      []byte `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftStorageUpdateMetaData) Reset() {
	*x = RaftStorageUpdateMetaData{}
	mi := &file_raftcommands_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStorageUpdateMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStorageUpdateMetaData) ProtoMessage() {}

func (x *RaftStorageUpdateMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStorageUpdateMetaData.ProtoReflect.Descriptor instead.
func (*RaftStorageUpdateMetaData) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{10}
}

func (x *RaftStorageUpdateMetaData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RaftStorageUpdateMetaData) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RaftCreateStorage creates a new storage with an assigned ID.
type RaftCreateStorage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal storage ID assigned by the system.
	StorageId uint32 `protobuf:"varint,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	// Storage creation parameters.
	Storage       *protobuf.CreateStorageRequest `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCreateStorage) Reset() {
	*x = RaftCreateStorage{}
	mi := &file_raftcommands_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCreateStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCreateStorage) ProtoMessage() {}

func (x *RaftCreateStorage) ProtoReflect() protoreflect.Message {
	mi := &file_raftcommands_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCreateStorage.ProtoReflect.Descriptor instead.
func (*RaftCreateStorage) Descriptor() ([]byte, []int) {
	return file_raftcommands_proto_rawDescGZIP(), []int{11}
}

func (x *RaftCreateStorage) GetStorageId() uint32 {
	if x != nil {
		return x.StorageId
	}
	return 0
}

func (x *RaftCreateStorage) GetStorage() *protobuf.CreateStorageRequest {
	if x != nil {
		return x.Storage
	}
	return nil
}

var File_raftcommands_proto protoreflect.FileDescriptor

const file_raftcommands_proto_rawDesc = "" +
	"\n" +
	"\x12raftcommands.proto\x12\x1eio.clbs.octopusmq.grpc.raftcmd\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0emessages.proto\"\xa0\a\n" +
	"\vRaftCommand\x12T\n" +
	"\fcreate_queue\x18\x01 \x01(\v2/.io.clbs.octopusmq.grpc.raftcmd.RaftCreateQueueH\x00R\vcreateQueue\x12S\n" +
	"\fdelete_queue\x18\x02 \x01(\v2..io.clbs.octopusmq.protobuf.DeleteQueueRequestH\x00R\vdeleteQueue\x12d\n" +
	"\x12pause_resume_queue\x18\x03 \x01(\v24.io.clbs.octopusmq.grpc.raftcmd.RaftPauseResumeQueueH\x00R\x10pauseResumeQueue\x12Q\n" +
	"\vpurge_items\x18\x04 \x01(\v2..io.clbs.octopusmq.grpc.raftcmd.RaftPurgeItemsH\x00R\n" +
	"purgeItems\x12`\n" +
	"\x10storage_commands\x18\x05 \x01(\v23.io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommandsH\x00R\x0fstorageCommands\x12d\n" +
	"\x12storage_delete_ids\x18\x06 \x01(\v24.io.clbs.octopusmq.grpc.raftcmd.RaftStorageDeleteIdsH\x00R\x10storageDeleteIds\x12N\n" +
	"\n" +
	"start_noop\x18\a \x01(\v2-.io.clbs.octopusmq.grpc.raftcmd.RaftStartNoopH\x00R\tstartNoop\x12S\n" +
	"\fresize_queue\x18\b \x01(\v2..io.clbs.octopusmq.protobuf.ResizeQueueRequestH\x00R\vresizeQueue\x12Z\n" +
	"\x0ecreate_storage\x18\t \x01(\v21.io.clbs.octopusmq.grpc.raftcmd.RaftCreateStorageH\x00R\rcreateStorage\x12Y\n" +
	"\x0edelete_storage\x18\n" +
	" \x01(\v20.io.clbs.octopusmq.protobuf.DeleteStorageRequestH\x00R\rdeleteStorageB\t\n" +
	"\acommand\"r\n" +
	"\x0fRaftCreateQueue\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\rR\aqueueId\x12D\n" +
	"\x05queue\x18\x02 \x01(\v2..io.clbs.octopusmq.protobuf.CreateQueueRequestR\x05queue\"K\n" +
	"\x14RaftPauseResumeQueue\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x14\n" +
	"\x05pause\x18\x02 \x01(\bR\x05pause\"\x10\n" +
	"\x0eRaftPurgeItems\"^\n" +
	"\rRaftStartNoop\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"u\n" +
	"\x13RaftStorageCommands\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12N\n" +
	"\bcommands\x18\x02 \x03(\v22.io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommandR\bcommands\"(\n" +
	"\x14RaftStorageDeleteIds\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"\xe4\x02\n" +
	"\x12RaftStorageCommand\x12K\n" +
	"\x06delete\x18\x01 \x01(\v21.io.clbs.octopusmq.grpc.raftcmd.RaftStorageDeleteH\x00R\x06delete\x12K\n" +
	"\x06insert\x18\x02 \x01(\v21.io.clbs.octopusmq.grpc.raftcmd.RaftStorageChangeH\x00R\x06insert\x12K\n" +
	"\x06update\x18\x03 \x01(\v21.io.clbs.octopusmq.grpc.raftcmd.RaftStorageChangeH\x00R\x06update\x12\\\n" +
	"\vupdate_meta\x18\x04 \x01(\v29.io.clbs.octopusmq.grpc.raftcmd.RaftStorageUpdateMetaDataH\x00R\n" +
	"updateMetaB\t\n" +
	"\acommand\"#\n" +
	"\x11RaftStorageDelete\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"S\n" +
	"\x11RaftStorageChange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\fR\bmetadata\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"G\n" +
	"\x19RaftStorageUpdateMetaData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\fR\bmetadata\"~\n" +
	"\x11RaftCreateStorage\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\rR\tstorageId\x12J\n" +
	"\astorage\x18\x02 \x01(\v20.io.clbs.octopusmq.protobuf.CreateStorageRequestR\astorageB0Z.github.com/clbs-io/octopusmq/pkg/grpcraftcmdpbb\x06proto3"

var (
	file_raftcommands_proto_rawDescOnce sync.Once
	file_raftcommands_proto_rawDescData []byte
)

func file_raftcommands_proto_rawDescGZIP() []byte {
	file_raftcommands_proto_rawDescOnce.Do(func() {
		file_raftcommands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftcommands_proto_rawDesc), len(file_raftcommands_proto_rawDesc)))
	})
	return file_raftcommands_proto_rawDescData
}

var file_raftcommands_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_raftcommands_proto_goTypes = []any{
	(*RaftCommand)(nil),                   // 0: io.clbs.octopusmq.grpc.raftcmd.RaftCommand
	(*RaftCreateQueue)(nil),               // 1: io.clbs.octopusmq.grpc.raftcmd.RaftCreateQueue
	(*RaftPauseResumeQueue)(nil),          // 2: io.clbs.octopusmq.grpc.raftcmd.RaftPauseResumeQueue
	(*RaftPurgeItems)(nil),                // 3: io.clbs.octopusmq.grpc.raftcmd.RaftPurgeItems
	(*RaftStartNoop)(nil),                 // 4: io.clbs.octopusmq.grpc.raftcmd.RaftStartNoop
	(*RaftStorageCommands)(nil),           // 5: io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommands
	(*RaftStorageDeleteIds)(nil),          // 6: io.clbs.octopusmq.grpc.raftcmd.RaftStorageDeleteIds
	(*RaftStorageCommand)(nil),            // 7: io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommand
	(*RaftStorageDelete)(nil),             // 8: io.clbs.octopusmq.grpc.raftcmd.RaftStorageDelete
	(*RaftStorageChange)(nil),             // 9: io.clbs.octopusmq.grpc.raftcmd.RaftStorageChange
	(*RaftStorageUpdateMetaData)(nil),     // 10: io.clbs.octopusmq.grpc.raftcmd.RaftStorageUpdateMetaData
	(*RaftCreateStorage)(nil),             // 11: io.clbs.octopusmq.grpc.raftcmd.RaftCreateStorage
	(*protobuf.DeleteQueueRequest)(nil),   // 12: io.clbs.octopusmq.protobuf.DeleteQueueRequest
	(*protobuf.ResizeQueueRequest)(nil),   // 13: io.clbs.octopusmq.protobuf.ResizeQueueRequest
	(*protobuf.DeleteStorageRequest)(nil), // 14: io.clbs.octopusmq.protobuf.DeleteStorageRequest
	(*protobuf.CreateQueueRequest)(nil),   // 15: io.clbs.octopusmq.protobuf.CreateQueueRequest
	(*timestamppb.Timestamp)(nil),         // 16: google.protobuf.Timestamp
	(*protobuf.CreateStorageRequest)(nil), // 17: io.clbs.octopusmq.protobuf.CreateStorageRequest
}
var file_raftcommands_proto_depIdxs = []int32{
	1,  // 0: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.create_queue:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftCreateQueue
	12, // 1: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.delete_queue:type_name -> io.clbs.octopusmq.protobuf.DeleteQueueRequest
	2,  // 2: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.pause_resume_queue:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftPauseResumeQueue
	3,  // 3: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.purge_items:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftPurgeItems
	5,  // 4: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.storage_commands:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommands
	6,  // 5: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.storage_delete_ids:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftStorageDeleteIds
	4,  // 6: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.start_noop:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftStartNoop
	13, // 7: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.resize_queue:type_name -> io.clbs.octopusmq.protobuf.ResizeQueueRequest
	11, // 8: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.create_storage:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftCreateStorage
	14, // 9: io.clbs.octopusmq.grpc.raftcmd.RaftCommand.delete_storage:type_name -> io.clbs.octopusmq.protobuf.DeleteStorageRequest
	15, // 10: io.clbs.octopusmq.grpc.raftcmd.RaftCreateQueue.queue:type_name -> io.clbs.octopusmq.protobuf.CreateQueueRequest
	16, // 11: io.clbs.octopusmq.grpc.raftcmd.RaftStartNoop.start_time:type_name -> google.protobuf.Timestamp
	7,  // 12: io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommands.commands:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommand
	8,  // 13: io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommand.delete:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftStorageDelete
	9,  // 14: io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommand.insert:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftStorageChange
	9,  // 15: io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommand.update:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftStorageChange
	10, // 16: io.clbs.octopusmq.grpc.raftcmd.RaftStorageCommand.update_meta:type_name -> io.clbs.octopusmq.grpc.raftcmd.RaftStorageUpdateMetaData
	17, // 17: io.clbs.octopusmq.grpc.raftcmd.RaftCreateStorage.storage:type_name -> io.clbs.octopusmq.protobuf.CreateStorageRequest
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_raftcommands_proto_init() }
func file_raftcommands_proto_init() {
	if File_raftcommands_proto != nil {
		return
	}
	file_raftcommands_proto_msgTypes[0].OneofWrappers = []any{
		(*RaftCommand_CreateQueue)(nil),
		(*RaftCommand_DeleteQueue)(nil),
		(*RaftCommand_PauseResumeQueue)(nil),
		(*RaftCommand_PurgeItems)(nil),
		(*RaftCommand_StorageCommands)(nil),
		(*RaftCommand_StorageDeleteIds)(nil),
		(*RaftCommand_StartNoop)(nil),
		(*RaftCommand_ResizeQueue)(nil),
		(*RaftCommand_CreateStorage)(nil),
		(*RaftCommand_DeleteStorage)(nil),
	}
	file_raftcommands_proto_msgTypes[7].OneofWrappers = []any{
		(*RaftStorageCommand_Delete)(nil),
		(*RaftStorageCommand_Insert)(nil),
		(*RaftStorageCommand_Update)(nil),
		(*RaftStorageCommand_UpdateMeta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftcommands_proto_rawDesc), len(file_raftcommands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raftcommands_proto_goTypes,
		DependencyIndexes: file_raftcommands_proto_depIdxs,
		MessageInfos:      file_raftcommands_proto_msgTypes,
	}.Build()
	File_raftcommands_proto = out.File
	file_raftcommands_proto_goTypes = nil
	file_raftcommands_proto_depIdxs = nil
}
