// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: queues.proto

package grpcpb

import (
	protobuf "github.com/clbs-io/octopusmq/api/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_queues_proto protoreflect.FileDescriptor

const file_queues_proto_rawDesc = "" +
	"\n" +
	"\fqueues.proto\x12\x16io.clbs.octopusmq.grpc\x1a\x0emessages.proto2s\n" +
	"\rQueuesService\x12b\n" +
	"\aConnect\x12(.io.clbs.octopusmq.protobuf.QueueRequest\x1a).io.clbs.octopusmq.protobuf.QueueResponse(\x010\x01B)Z'github.com/clbs-io/octopusmq/pkg/grpcpbb\x06proto3"

var file_queues_proto_goTypes = []any{
	(*protobuf.QueueRequest)(nil),  // 0: io.clbs.octopusmq.protobuf.QueueRequest
	(*protobuf.QueueResponse)(nil), // 1: io.clbs.octopusmq.protobuf.QueueResponse
}
var file_queues_proto_depIdxs = []int32{
	0, // 0: io.clbs.octopusmq.grpc.QueuesService.Connect:input_type -> io.clbs.octopusmq.protobuf.QueueRequest
	1, // 1: io.clbs.octopusmq.grpc.QueuesService.Connect:output_type -> io.clbs.octopusmq.protobuf.QueueResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_queues_proto_init() }
func file_queues_proto_init() {
	if File_queues_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queues_proto_rawDesc), len(file_queues_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queues_proto_goTypes,
		DependencyIndexes: file_queues_proto_depIdxs,
	}.Build()
	File_queues_proto = out.File
	file_queues_proto_goTypes = nil
	file_queues_proto_depIdxs = nil
}
