// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: cluster_management.proto

package grpcclustermgmtpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MemberState is the replication state of a replica as seen by the leader.
type MemberState int32

const (
	// MEMBER_STATE_UNSPECIFIED is never returned by a broker that reports the state.
	MemberState_MEMBER_STATE_UNSPECIFIED MemberState = 0
	// MEMBER_STATE_REPLICATE means the replica follows the leader's log and receives entries steadily.
	MemberState_MEMBER_STATE_REPLICATE MemberState = 1
	// MEMBER_STATE_PROBE means the leader is still finding the point where the replica's log matches its own.
	MemberState_MEMBER_STATE_PROBE MemberState = 2
	// MEMBER_STATE_SNAPSHOT means the replica is being brought up to date from a snapshot.
	MemberState_MEMBER_STATE_SNAPSHOT MemberState = 3
	// MEMBER_STATE_NOT_A_MEMBER means the replica is not part of the cluster's voter set and has no progress.
	MemberState_MEMBER_STATE_NOT_A_MEMBER MemberState = 4
)

// Enum value maps for MemberState.
var (
	MemberState_name = map[int32]string{
		0: "MEMBER_STATE_UNSPECIFIED",
		1: "MEMBER_STATE_REPLICATE",
		2: "MEMBER_STATE_PROBE",
		3: "MEMBER_STATE_SNAPSHOT",
		4: "MEMBER_STATE_NOT_A_MEMBER",
	}
	MemberState_value = map[string]int32{
		"MEMBER_STATE_UNSPECIFIED":  0,
		"MEMBER_STATE_REPLICATE":    1,
		"MEMBER_STATE_PROBE":        2,
		"MEMBER_STATE_SNAPSHOT":     3,
		"MEMBER_STATE_NOT_A_MEMBER": 4,
	}
)

func (x MemberState) Enum() *MemberState {
	p := new(MemberState)
	*p = x
	return p
}

func (x MemberState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberState) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_management_proto_enumTypes[0].Descriptor()
}

func (MemberState) Type() protoreflect.EnumType {
	return &file_cluster_management_proto_enumTypes[0]
}

func (x MemberState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberState.Descriptor instead.
func (MemberState) EnumDescriptor() ([]byte, []int) {
	return file_cluster_management_proto_rawDescGZIP(), []int{0}
}

// Member describes one replica of the cluster.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ordinal is the index of the replica in the StatefulSet.
	Ordinal uint32 `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	// id is the Raft node id of the replica.
	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// voter tells whether the replica is a voting member of the cluster.
	Voter bool `protobuf:"varint,3,opt,name=voter,proto3" json:"voter,omitempty"`
	// leader tells whether the replica is the current leader.
	Leader bool `protobuf:"varint,4,opt,name=leader,proto3" json:"leader,omitempty"`
	// state is the replication state of the replica.
	State MemberState `protobuf:"varint,5,opt,name=state,proto3,enum=io.clbs.octopusmq.grpc.management.MemberState" json:"state,omitempty"`
	// match_index is the highest log index known to be replicated on the replica.
	MatchIndex uint64 `protobuf:"varint,6,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	// lag is the number of log entries the replica is behind the leader's last index.
	Lag uint64 `protobuf:"varint,7,opt,name=lag,proto3" json:"lag,omitempty"`
	// last_heard_seconds is the time since the leader last heard from the replica, negative when it never did.
	LastHeardSeconds float64 `protobuf:"fixed64,8,opt,name=last_heard_seconds,json=lastHeardSeconds,proto3" json:"last_heard_seconds,omitempty"`
	// snapshot_in_flight tells whether a data snapshot is being streamed to the replica.
	SnapshotInFlight bool `protobuf:"varint,9,opt,name=snapshot_in_flight,json=snapshotInFlight,proto3" json:"snapshot_in_flight,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_cluster_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_cluster_management_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *Member) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetVoter() bool {
	if x != nil {
		return x.Voter
	}
	return false
}

func (x *Member) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *Member) GetState() MemberState {
	if x != nil {
		return x.State
	}
	return MemberState_MEMBER_STATE_UNSPECIFIED
}

func (x *Member) GetMatchIndex() uint64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

func (x *Member) GetLag() uint64 {
	if x != nil {
		return x.Lag
	}
	return 0
}

func (x *Member) GetLastHeardSeconds() float64 {
	if x != nil {
		return x.LastHeardSeconds
	}
	return 0
}

func (x *Member) GetSnapshotInFlight() bool {
	if x != nil {
		return x.SnapshotInFlight
	}
	return false
}

// ListMembersResponse lists the replicas of the cluster.
type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_cluster_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_cluster_management_proto_rawDescGZIP(), []int{1}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

// DestroyMemberRequest selects the replica to remove.
type DestroyMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ordinal is the index of the replica in the StatefulSet.
	Ordinal       uint32 `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyMemberRequest) Reset() {
	*x = DestroyMemberRequest{}
	mi := &file_cluster_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyMemberRequest) ProtoMessage() {}

func (x *DestroyMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyMemberRequest.ProtoReflect.Descriptor instead.
func (*DestroyMemberRequest) Descriptor() ([]byte, []int) {
	return file_cluster_management_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyMemberRequest) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

// DestroyMemberResponse reports the removed replica.
type DestroyMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// removed_id is the Raft node id of the removed replica.
	RemovedId     uint64 `protobuf:"varint,1,opt,name=removed_id,json=removedId,proto3" json:"removed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyMemberResponse) Reset() {
	*x = DestroyMemberResponse{}
	mi := &file_cluster_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyMemberResponse) ProtoMessage() {}

func (x *DestroyMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyMemberResponse.ProtoReflect.Descriptor instead.
func (*DestroyMemberResponse) Descriptor() ([]byte, []int) {
	return file_cluster_management_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyMemberResponse) GetRemovedId() uint64 {
	if x != nil {
		return x.RemovedId
	}
	return 0
}

var File_cluster_management_proto protoreflect.FileDescriptor

const file_cluster_management_proto_rawDesc = "" +
	"\n" +
	"\x18cluster_management.proto\x12!io.clbs.octopusmq.grpc.management\x1a\x1bgoogle/protobuf/empty.proto\"\xb5\x02\n" +
	"\x06Member\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\rR\aordinal\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x14\n" +
	"\x05voter\x18\x03 \x01(\bR\x05voter\x12\x16\n" +
	"\x06leader\x18\x04 \x01(\bR\x06leader\x12D\n" +
	"\x05state\x18\x05 \x01(\x0e2..io.clbs.octopusmq.grpc.management.MemberStateR\x05state\x12\x1f\n" +
	"\vmatch_index\x18\x06 \x01(\x04R\n" +
	"matchIndex\x12\x10\n" +
	"\x03lag\x18\a \x01(\x04R\x03lag\x12,\n" +
	"\x12last_heard_seconds\x18\b \x01(\x01R\x10lastHeardSeconds\x12,\n" +
	"\x12snapshot_in_flight\x18\t \x01(\bR\x10snapshotInFlight\"Z\n" +
	"\x13ListMembersResponse\x12C\n" +
	"\amembers\x18\x01 \x03(\v2).io.clbs.octopusmq.grpc.management.MemberR\amembers\"0\n" +
	"\x14DestroyMemberRequest\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\rR\aordinal\"6\n" +
	"\x15DestroyMemberResponse\x12\x1d\n" +
	"\n" +
	"removed_id\x18\x01 \x01(\x04R\tremovedId*\x99\x01\n" +
	"\vMemberState\x12\x1c\n" +
	"\x18MEMBER_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MEMBER_STATE_REPLICATE\x10\x01\x12\x16\n" +
	"\x12MEMBER_STATE_PROBE\x10\x02\x12\x19\n" +
	"\x15MEMBER_STATE_SNAPSHOT\x10\x03\x12\x1d\n" +
	"\x19MEMBER_STATE_NOT_A_MEMBER\x10\x042\xf4\x01\n" +
	"\x0eClusterService\x12]\n" +
	"\vListMembers\x12\x16.google.protobuf.Empty\x1a6.io.clbs.octopusmq.grpc.management.ListMembersResponse\x12\x82\x01\n" +
	"\rDestroyMember\x127.io.clbs.octopusmq.grpc.management.DestroyMemberRequest\x1a8.io.clbs.octopusmq.grpc.management.DestroyMemberResponseB4Z2github.com/clbs-io/octopusmq/pkg/grpcclustermgmtpbb\x06proto3"

var (
	file_cluster_management_proto_rawDescOnce sync.Once
	file_cluster_management_proto_rawDescData []byte
)

func file_cluster_management_proto_rawDescGZIP() []byte {
	file_cluster_management_proto_rawDescOnce.Do(func() {
		file_cluster_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_management_proto_rawDesc), len(file_cluster_management_proto_rawDesc)))
	})
	return file_cluster_management_proto_rawDescData
}

var file_cluster_management_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_management_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cluster_management_proto_goTypes = []any{
	(MemberState)(0),              // 0: io.clbs.octopusmq.grpc.management.MemberState
	(*Member)(nil),                // 1: io.clbs.octopusmq.grpc.management.Member
	(*ListMembersResponse)(nil),   // 2: io.clbs.octopusmq.grpc.management.ListMembersResponse
	(*DestroyMemberRequest)(nil),  // 3: io.clbs.octopusmq.grpc.management.DestroyMemberRequest
	(*DestroyMemberResponse)(nil), // 4: io.clbs.octopusmq.grpc.management.DestroyMemberResponse
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_cluster_management_proto_depIdxs = []int32{
	0, // 0: io.clbs.octopusmq.grpc.management.Member.state:type_name -> io.clbs.octopusmq.grpc.management.MemberState
	1, // 1: io.clbs.octopusmq.grpc.management.ListMembersResponse.members:type_name -> io.clbs.octopusmq.grpc.management.Member
	5, // 2: io.clbs.octopusmq.grpc.management.ClusterService.ListMembers:input_type -> google.protobuf.Empty
	3, // 3: io.clbs.octopusmq.grpc.management.ClusterService.DestroyMember:input_type -> io.clbs.octopusmq.grpc.management.DestroyMemberRequest
	2, // 4: io.clbs.octopusmq.grpc.management.ClusterService.ListMembers:output_type -> io.clbs.octopusmq.grpc.management.ListMembersResponse
	4, // 5: io.clbs.octopusmq.grpc.management.ClusterService.DestroyMember:output_type -> io.clbs.octopusmq.grpc.management.DestroyMemberResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cluster_management_proto_init() }
func file_cluster_management_proto_init() {
	if File_cluster_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_management_proto_rawDesc), len(file_cluster_management_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_management_proto_goTypes,
		DependencyIndexes: file_cluster_management_proto_depIdxs,
		EnumInfos:         file_cluster_management_proto_enumTypes,
		MessageInfos:      file_cluster_management_proto_msgTypes,
	}.Build()
	File_cluster_management_proto = out.File
	file_cluster_management_proto_goTypes = nil
	file_cluster_management_proto_depIdxs = nil
}
