// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: cluster_management.proto

package grpcclustermgmtpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterService_ListMembers_FullMethodName   = "/io.clbs.octopusmq.grpc.management.ClusterService/ListMembers"
	ClusterService_DestroyMember_FullMethodName = "/io.clbs.octopusmq.grpc.management.ClusterService/DestroyMember"
)

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterService provides cluster membership inspection and replica maintenance operations.
type ClusterServiceClient interface {
	// ListMembers returns every replica of the cluster, including replicas that are currently not voters,
	// such as a destroyed replica before it rejoins. It is served by the leader.
	ListMembers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMembersResponse, error)
	// DestroyMember removes a replica from the cluster. The removed replica wipes its local data and
	// rejoins the cluster at its next start, resynchronizing from the leader. Only one replica is
	// destroyed at a time, and the cluster keeps a working majority throughout.
	//
	// A replica that is already not a voter is reported as removed, so repeating the call is harmless.
	//
	// Status codes:
	//   - InvalidArgument: the ordinal is outside the set of replicas of the cluster.
	//   - FailedPrecondition: another replica is still resynchronizing, or removing the replica would leave
	//     the cluster without a working majority. The message names the replicas involved.
	//   - Unavailable: leadership moved while the call was served. Retry the call; the new leader
	//     evaluates it again.
	//   - DeadlineExceeded: the removal was proposed but did not take effect in time. Check ListMembers
	//     and repeat the call.
	DestroyMember(ctx context.Context, in *DestroyMemberRequest, opts ...grpc.CallOption) (*DestroyMemberResponse, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) ListMembers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, ClusterService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) DestroyMember(ctx context.Context, in *DestroyMemberRequest, opts ...grpc.CallOption) (*DestroyMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyMemberResponse)
	err := c.cc.Invoke(ctx, ClusterService_DestroyMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility.
//
// ClusterService provides cluster membership inspection and replica maintenance operations.
type ClusterServiceServer interface {
	// ListMembers returns every replica of the cluster, including replicas that are currently not voters,
	// such as a destroyed replica before it rejoins. It is served by the leader.
	ListMembers(context.Context, *emptypb.Empty) (*ListMembersResponse, error)
	// DestroyMember removes a replica from the cluster. The removed replica wipes its local data and
	// rejoins the cluster at its next start, resynchronizing from the leader. Only one replica is
	// destroyed at a time, and the cluster keeps a working majority throughout.
	//
	// A replica that is already not a voter is reported as removed, so repeating the call is harmless.
	//
	// Status codes:
	//   - InvalidArgument: the ordinal is outside the set of replicas of the cluster.
	//   - FailedPrecondition: another replica is still resynchronizing, or removing the replica would leave
	//     the cluster without a working majority. The message names the replicas involved.
	//   - Unavailable: leadership moved while the call was served. Retry the call; the new leader
	//     evaluates it again.
	//   - DeadlineExceeded: the removal was proposed but did not take effect in time. Check ListMembers
	//     and repeat the call.
	DestroyMember(context.Context, *DestroyMemberRequest) (*DestroyMemberResponse, error)
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServiceServer struct{}

func (UnimplementedClusterServiceServer) ListMembers(context.Context, *emptypb.Empty) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedClusterServiceServer) DestroyMember(context.Context, *DestroyMemberRequest) (*DestroyMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyMember not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}
func (UnimplementedClusterServiceServer) testEmbeddedByValue()                        {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ListMembers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_DestroyMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).DestroyMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_DestroyMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).DestroyMember(ctx, req.(*DestroyMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.clbs.octopusmq.grpc.management.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMembers",
			Handler:    _ClusterService_ListMembers_Handler,
		},
		{
			MethodName: "DestroyMember",
			Handler:    _ClusterService_DestroyMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster_management.proto",
}
